class Constants:
    TEST_FOLDER_ID = 'test_folder_id'
    KEY_FILE = 'key_file'
    CONFIG_FILE = 'config_file'
    TEST_ORG_ID = 'test_org_id'
    TEST_FOLDER_NAME = 'test_folder_name'
    BQ_PROJECT_ID = 'bq_project_id'
    DATASET_ID = 'dataset_id'
    TABLE_NAME = 'table_name'
    FOLDER_NAME_LEVEL_1 = 'folder_name_level_1'
    FOLDER_NAME_LEVEL_2 = 'folder_name_level_2'
    FOLDER_LEVEL_1 = 'folder_level_1'
    FOLDER_LEVEL_2 = 'folder_level_2'
    ORG_DISPLAY_NAME = 'org_display_name'
    PROJECT_ID = 'projectid_for_ancestry_test'
    ERROR_FILE = 'test_get_ancestry.err'
